title: Faith Webb's Blog
description: A place for my thoughts.
github:
  is_project_page: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - ideas/2019-09-04.md
theme: jekyll-theme-modernist